Repository light5551/test_pr_automation, pull requests merged in 2019-07, with the labels that each got.

#6 Glazunov_Sergey_lb3
  Glazunov_Sergey_lb3/Glazunov_Sergey_lb3_report.pdf
Labels: Passed the structure test

#7 Glazunov_Sergey_lb4
  Glazunov_Sergey_lb4/Glazunov_Sergey_lb4_report.pdf
  Glazunov_Sergey_lb4/src/main.c
Labels: Passed the structure test, not_delivered

#10 Gavrilov_Andrew_lb3
  Gavrilov_Andrew_lb3/.~lock.Gavrilov_Andrew_lb3.docx#
  Gavrilov_Andrew_lb3/Gavrilov_Andrew_lb3.docx
  Gavrilov_Andrew_lb3/src/.main.c.swp
  Gavrilov_Andrew_lb3/src/main.c
Labels: Passed the structure test, passed

#9 Glazunov_Sergey_lb1
  Glazunov_Sergey_lb1/Glazunov_Sergey_lb1.pdf
  Glazunov_Sergey_lb1/src/main.c
Labels: Passed the structure test, passed
